# Generated by Django 5.2.5 on 2025-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
