# Generated by Django 5.2.5 on 2025-12-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_todoitem_due_date_todoitem_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='reminder_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes before due time to remind', null=True),
        ),
    ]
