# Generated by Django 5.2.5 on 2025-12-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_category_todoitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='repeat',
            field=models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10),
        ),
    ]
